name: Python CI

on: [push, workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: cache virtualenv
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-

      - name: Install dependencies
        shell: bash
        run: |
          python3 -m venv ./.venv
          source ./.venv/bin/activate
          pip install -r requirements.txt -e .
          pip install -U pylint pytest -e .
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Install repo project
        shell: bash
        run: |
          source ./.venv/bin/activate
          pip install -U pylint pytest

  lint:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Restore Python virtual environment
        uses: actions/cache@v4
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-

      - name: add pylint as a command from env
        shell: bash
        run: |
          ls -la ./.venv
          ls -la ./.venv/bin
          source ./.venv/bin/activate
          export PATH=$PATH:$(pwd)/.venv/bin

      - name: Lint Code
        shell: bash
        run: |
          pylint $(git ls-files '*.py')

  test:
    runs-on: ubuntu-latest
    needs: install
    env:
      ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
      ROBOFLOW_PROJECT_ID: ${{ secrets.ROBOFLOW_PROJECT_ID }}
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python virtual environment
        uses: actions/cache@v4
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-

      - name: Run tests
        shell: bash
        run: |
          pytest .
