name: Python CI

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Lint Code
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install -U pylint
          pylint $(git ls-files '*.py')

  test:
    runs-on: ubuntu-latest
    env:
      ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
      ROBOFLOW_PROJECT_ID: ${{ vars.ROBOFLOW_PROJECT_ID }}
      WORKSPACE: ${{ vars.WORKSPACE }}
      ROBOFLOW_PROJECT_VERSION: ${{ vars.ROBOFLOW_PROJECT_VERSION }}
      DATASET_FORMAT: ${{ vars.DATASET_FORMAT }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install -U pytest
          pytest --capture=sys --cov --disable-warnings -v --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        if: matrix.os == 'ubuntu-latest'
        with:
          file: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
