name: Python CI

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Lint Code
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install -U pylint
          pylint $(git ls-files '*.py')

  test:
    runs-on: ubuntu-latest
    env:
      ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
      ROBOFLOW_PROJECT_ID: ${{ secrets.ROBOFLOW_PROJECT_ID }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install -U pytest
          pytest .
